# Generated by Django 5.1.3 on 2024-12-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_raw_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_password', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
